export const OPEN_MODAL_USER = 'OPEN_MODAL_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_ERROR = 'Tài khoản hoặc mật khẩu không đúng!'
export const USER_INFO = 'USER_INFO'
export const LAY_THONG_TIN_PHIM = 'LAY_THONG_TIN_PHIM';
export const LAY_THONG_TIN_LICH_CHIEU_PHIM = 'LAY_THONG_TIN_LICH_CHIEU_PHIM';
export const LAY_THONG_TIN_NGUOI_DUNG = 'LAY_THONG_TIN_NGUOI_DUNG';
export const LAY_THONG_TIN_NGUOI_DUNG_UPDATE = 'LAY_THONG_TIN_NGUOI_DUNG_UPDATE';
